# Generated by Django 5.2 on 2025-04-13 07:42

import django.db.models.deletion
import hospital.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[hospital.validators.validate_age]),
        ),
    ]
